"""
End-to-end authentication flow tests for the security integration.

This test suite covers user registration, login, JWT token handling, and API access.
"""

import pytest
import os
import sys
from unittest.mock import patch, MagicMock
from fastapi.testclient import TestClient
from jose import jwt
from datetime import datetime, timedelta
from pathlib import Path

# Add backend to path to import modules
sys.path.insert(0, str(Path(__file__).parent / "backend"))

from backend.app.main import app
from backend.app.core.auth import SECRET_KEY, ALGORITHM
from backend.app.core.jwt_utils import verify_jwt_token, extract_user_id_from_token

# Set up test environment
os.environ["BETTER_AUTH_SECRET"] = "test-secret-key-for-testing-purposes-only"

@pytest.fixture
def client():
    """Create a test client for the FastAPI app."""
    return TestClient(app)

class TestUserRegistrationFlow:
    """Test user registration and authentication flows."""

    def test_user_registration_flow(self):
        """Test complete user registration flow."""
        client = TestClient(app)

        # Mock user registration data
        user_data = {
            "email": "testuser@example.com",
            "password": "securepassword123"
        }

        # In a real scenario, this would hit the Better Auth endpoint
        # For testing purposes, we'll simulate the flow

        # Registration would happen via Better Auth, then we'd receive a JWT
        # For testing, we'll create a mock token
        mock_token = jwt.encode({
            "sub": "123",
            "email": "testuser@example.com",
            "exp": datetime.utcnow() + timedelta(days=7)
        }, SECRET_KEY, algorithm=ALGORITHM)

        # Verify the token can be decoded
        payload = verify_jwt_token(mock_token)
        assert payload is not None
        assert payload["sub"] == "123"
        assert payload["email"] == "testuser@example.com"

    def test_user_login_flow(self):
        """Test complete user login flow."""
        client = TestClient(app)

        # Similar to registration, login would happen via Better Auth
        # Then we'd receive a JWT token that we can use for API access

        # Create a valid token for testing
        token = jwt.encode({
            "sub": "456",
            "email": "loggedinuser@example.com",
            "exp": datetime.utcnow() + timedelta(days=7)
        }, SECRET_KEY, algorithm=ALGORITHM)

        # Extract user ID from token
        user_id = extract_user_id_from_token(token)
        assert user_id == "456"

    def test_authentication_failure_scenarios(self):
        """Test various authentication failure scenarios."""

        # Test invalid token
        invalid_token_result = verify_jwt_token("invalid.token.here")
        assert invalid_token_result is None

        # Test expired token
        expired_token = jwt.encode({
            "sub": "789",
            "exp": datetime.utcnow() - timedelta(minutes=1)  # Expired 1 minute ago
        }, SECRET_KEY, algorithm=ALGORITHM)

        expired_result = verify_jwt_token(expired_token)
        assert expired_result is None

        # Test token without user ID
        token_without_sub = jwt.encode({
            "email": "user@example.com",
            "exp": datetime.utcnow() + timedelta(hours=1)
        }, SECRET_KEY, algorithm=ALGORITHM)

        user_id = extract_user_id_from_token(token_without_sub)
        assert user_id is None

class TestCrossServiceAuthentication:
    """Test cross-service authentication between frontend and backend."""

    def test_jwt_token_validation_backend(self):
        """Test that JWT tokens generated by Better Auth can be validated by FastAPI backend."""
        # Simulate a token that would be generated by Better Auth
        better_auth_token = jwt.encode({
            "sub": "999",  # User ID
            "email": "betterauthuser@example.com",
            "iat": datetime.utcnow(),
            "exp": datetime.utcnow() + timedelta(days=7),
            "jti": "unique-token-id"  # JWT ID
        }, SECRET_KEY, algorithm=ALGORITHM)

        # Backend should be able to validate this token
        payload = verify_jwt_token(better_auth_token)
        assert payload is not None
        assert payload["sub"] == "999"
        assert payload["email"] == "betterauthuser@example.com"

        # Extract user ID from token
        user_id = extract_user_id_from_token(better_auth_token)
        assert user_id == "999"

    def test_cross_service_user_isolation(self):
        """Test that user isolation is maintained across services."""
        # Create tokens for different users
        user_a_token = jwt.encode({
            "sub": "user_a",
            "exp": datetime.utcnow() + timedelta(hours=1)
        }, SECRET_KEY, algorithm=ALGORITHM)

        user_b_token = jwt.encode({
            "sub": "user_b",
            "exp": datetime.utcnow() + timedelta(hours=1)
        }, SECRET_KEY, algorithm=ALGORITHM)

        # Both tokens should be valid individually
        assert verify_jwt_token(user_a_token) is not None
        assert verify_jwt_token(user_b_token) is not None

        # Extract user IDs
        user_a_id = extract_user_id_from_token(user_a_token)
        user_b_id = extract_user_id_from_token(user_b_token)

        assert user_a_id == "user_a"
        assert user_b_id == "user_b"

        # User isolation check
        from backend.app.core.jwt_utils import validate_user_access
        assert validate_user_access("user_a", "user_a") is True
        assert validate_user_access("user_a", "user_b") is False
        assert validate_user_access("user_b", "user_a") is False
        assert validate_user_access("user_b", "user_b") is True

class TestExpiredTokenHandling:
    """Test handling of expired JWT tokens."""

    def test_expired_token_detection(self):
        """Test that expired tokens are properly detected."""
        from backend.app.core.jwt_utils import is_token_expired

        # Create an expired token
        expired_token = jwt.encode({
            "sub": "123",
            "exp": datetime.utcnow() - timedelta(minutes=1)  # Expired 1 minute ago
        }, SECRET_KEY, algorithm=ALGORITHM)

        assert is_token_expired(expired_token) is True

        # Create a valid token
        valid_token = jwt.encode({
            "sub": "123",
            "exp": datetime.utcnow() + timedelta(hours=1)  # Expires in 1 hour
        }, SECRET_KEY, algorithm=ALGORITHM)

        assert is_token_expired(valid_token) is False

    def test_authentication_with_expired_token(self):
        """Test authentication failure with expired token."""
        from backend.app.core.jwt_utils import authenticate_and_authorize
        from fastapi import HTTPException

        # Create an expired token
        expired_token = jwt.encode({
            "sub": "123",
            "exp": datetime.utcnow() - timedelta(minutes=1)  # Expired 1 minute ago
        }, SECRET_KEY, algorithm=ALGORITHM)

        # Attempt to authenticate with expired token should raise HTTPException
        with pytest.raises(HTTPException) as exc_info:
            authenticate_and_authorize(expired_token, "123")

        assert exc_info.value.status_code == 401

if __name__ == "__main__":
    pytest.main([__file__, "-v"])