[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic",
    "fastapi",
    "passlib[bcrypt]",
    "pyjwt",
    "psycopg2",
    "python-dotenv",
    "python-jose[cryptography]",
    "sqlmodel",
    "uvicorn",
    "psycopg>=3.3.2",
    "uuid>=1.30",
]
